### ISSUE TITLE
Truth Social integration? 

### ISSUE THREAD

**Issue by Jxck-S** [Jxck-S/plane-notify#101]
Hate me or love me idc, I'm verified on Truth with 13k so why not share there? Does anyone know how I can integrate into the API?https://truthsocial.com/@ElonJet

**Comment by alexgleason** [comment]
The implementation in #90 should work.

**Comment by Jxck-S** [comment]
> The implementation in #90 should work.

From what I'm aware it's not available to connect to that endpoint on Truth. While truth is Mastodon based it's heavily modified.

**Comment by Jxck-S** [comment]
Should be coming soon in contact with Truth Social Team

**Comment by Jxck-S** [comment]
TruthSocial is dying anyway not worth my time. They sent me API documentation but it didn't work.
