### ISSUE TITLE
Pandas module missing - Docker requirements

### ISSUE THREAD

**Issue by brickhousetech** [Jxck-S/plane-notify#107]
Appears the Pandas module is missing in the Docker requirements.  Added and rebuilt.  Will report back when another fuel check occurs as that's when it crashed.

**Comment by brickhousetech** [comment]
Created PR for missing packages.  After changes indicated, fuel calculations function correctly with no errors or crashes.

**Comment by makrsmark** [comment]
fixed by 50bf15214819c322b353e6febe6e6ef25c790c15
