### ISSUE TITLE
MAP configs not consistent

### ISSUE THREAD

**Issue by makrsmark** [Jxck-S/plane-notify#120]
The config examples have MAP/OPTION in `mainconf.ini.example` while MAP/OPTION is in `plane1.ini.exmple`. The code all map configs in the plane conf, not the main conf. What do we want to go with?

**Comment by Jxck-S** [comment]
Let's go with one option in main config, makes the most sense, I think. It looks like the current code does it this way now.

**Comment by Jxck-S** [comment]
Oh actually, its in both for a reason. The one in the main is for choosing tar1090/google maps while the other in-plane configs are for choosing map overlays.

**Comment by makrsmark** [comment]
Looks like this is now consistent in the code - use `mainconf.ini` - i'll update my config accordingly
