### ISSUE TITLE
Discord Community Violations

### ISSUE THREAD

**Issue by gredinger** [Jxck-S/plane-notify#124]
Hiya,

I joined the discord community to discuss tracking jets. I had a disagreement with a moderator who went on to insult me merely for posting links/topics in the relative channels.

Can you go ahead and remove the discord moderator for violating  the community terms?

**Comment by gredinger** [comment]
![image](https://github.com/Jxck-S/plane-notify/assets/4158363/82abb7a5-5680-47c0-90ce-f0752e44f3ba)

This was the text after muting me. I blocked him. I messaged the admin reporting the behavior. I was unmuted [I think by the admin]. I posted several links that sourced my claims.

I made the mistake of viewing blocked messages in which the moderator issued additional personal insults and I was removed from the discord server.

**Comment by Jxck-S** [comment]
You should be able to rejoin

**Comment by gredinger** [comment]
Sadly not; 
![image](https://github.com/Jxck-S/plane-notify/assets/4158363/ee24e88f-472b-48c0-94eb-ce90eb51c986)
Thanks for the quick response

**Comment by gredinger** [comment]
It seems the specific moderator in question has removed me from the community again.

No reason was given. Any post I made was directly quoted from news articles in the relevant channels. I believe one of the admins made a political joke which I followed up on.

I've had positive engagement from developers of this community, but there seems to be some pro-Tesla fans who really cannot allow any criticism of Tesla to leak into their areas.

Mind you, several members there consider "phantom braking" issues with Tesla to be a "conspiracy", so therefore discussion of that topic can lead to a ban... even when it's heavily documented by news media [and now there's even a leak [ https://jalopnik.com/whistleblower-drops-100-gigabytes-of-tesla-secrets-to-g-1850476542 ]]

Overall, it's not a surprise pro-Elon Musk folks operate within this project given how Elon had a goal to shut down this project

**Comment by gredinger** [comment]
I'm still unsure how sharing news about Tesla in the "#tesla" channel was against the community guidelines. I do know there were people who were rather uncivil regarding the quotes from the news articles. It was interesting that even though the words weren't my words, I was attacked for them and the moderators of the community allowed the attacks.

I was told Tesla braking problems were a "conspiracy" and "made up". Therefore, any discussion of the "tesla braking problem" is "conspiracy" talk. The thing is... it's not a conspiracy, and the quotes were directly from reputable news articles/journist;

https://arstechnica.com/cars/2023/05/massive-trove-of-tesla-files-contains-thousands-of-safety-complaints/

Allowing Musk to manipulate your community into a bunch of Musk supporters is a total loss.

**Comment by gredinger** [comment]
I'm no longer as interested in this project.
