### ISSUE TITLE
OSM Attribution

### ISSUE THREAD

**Issue by matkoniecz** [Jxck-S/plane-notify#135]
It is quite nice to see OpenStreetMap data being used, but please remember that you need to credit it!

See https://www.openstreetmap.org/copyright

putting "background map (C) OpenStreetMap, ODBL license" below TheAirTraffic.com in the left should be good enough - and there is space there

(I tried to message https://www.facebook.com/ElonJet account on 2024-01-24 but have no response so far)

![426655042_399516049397508_4879067088463657735_n](https://github.com/Jxck-S/plane-notify/assets/899988/d3098f50-5845-41d4-87ce-b70bdd9c5506)

**Comment by Jxck-S** [comment]
Will fix this, this was a mistake in some commits/changes of code.

**Comment by matkoniecz** [comment]
So older version had an attribution?

**Comment by matkoniecz** [comment]
I see that say https://www.facebook.com/photo/?fbid=432565362759243&set=pb.100080173478533.-2207520000 changed map format recently - but at least still without attribution (not sure is it still coming from plane-notify)

**Comment by matkoniecz** [comment]
@Jxck-S Do you have plans to fix this ongoing plagiarism?

**Comment by ghost** [comment]
Looking at https://mastodon.social/@elonjet

maps got attribution till [28 Nov 2023](https://mastodon.social/@elonjet/111487617978438661), after that the attribution is missing.

Attribution could also be added in the content of the post, until a commit that fix the images is released. Probably this will takes less time.

**Comment by Jxck-S** [comment]
This is fixed now sorry for the delay. Please note the accounts you mentioned are gone now on Meta platforms including Facebook, they are only on alternative platforms.

**Comment by Jxck-S** [comment]
It's on the bottom left of the images now, as well as on our attributions page on our website. [https://grndcntrl.net/attributions/](https://grndcntrl.net/attributions/)
