### ISSUE TITLE
Data API Request. 

### ISSUE THREAD

**Issue by ilyasse005** [Jxck-S/plane-notify#138]
![Screenshot from 2024-07-25 20-53-02](https://github.com/user-attachments/assets/a5d763a2-ac45-44b5-9473-0ae8cc174515)

**Comment by ilyasse005** [comment]
![Screenshot from 2024-07-25 20-56-55](https://github.com/user-attachments/assets/aedf77c6-fb9d-498a-a2cd-0fd4c8efceb9)
![Screenshot from 2024-07-25 20-57-44](https://github.com/user-attachments/assets/9a021635-875d-4bf7-a7d1-ad43cb0ba135)

**Comment by Jxck-S** [comment]
Depending on how many planes you want to track, the ADSBExchange RapidAPI will work fine if you use the right settings. But if you need to track a lot, you need the official API from them. However, ADSBExchange charges a lot (They got bought by a JetNet and primarily serve enterprise applications where they charge thousands of dollars now. I would use [TheAirTraffic.com](https://TheAirTraffic.com). Contact me at JackHSweeney@protonmail.com for setup
