### ISSUE TITLE
feature request:

### ISSUE THREAD

**Issue by ivannunyadambiz** [Jxck-S/plane-notify#23]
calculate and announce released CO2 per flight. should be pretty easy to do.

**Comment by Jxck-S** [comment]
Yep working on it right now almost done. If you're in the discord you'll see it working.

**Comment by Jxck-S** [comment]
It's working, I just need to upload it to GitHub.

**Comment by NomsterDude** [comment]
@Jxck-S you may want to close this issue since you uploaded the "solution" :)
