### ISSUE TITLE
Export Data into mysql-DB?

### ISSUE THREAD

**Issue by lars776** [Jxck-S/plane-notify#25]
Hi!
I use this script on my own server. It works good!
Is it possible to add an option in the ini file to export the data into an mysql-database? The aircraft-data without the taken picture.

Regards,
Lars

**Comment by Jxck-S** [comment]
Possibly in the future but currently its not implemented, if I add it ill probably use Postgres

**Comment by Jxck-S** [comment]
Postgres logging is coming in a release soon.
