### ISSUE TITLE
Cannot Run __main__.py

### ISSUE THREAD

**Issue by mzmznasipadang** [Jxck-S/plane-notify#30]
When trying to run __main.py__, the answer is
/root/.local/share/virtualenvs/root-BuDEOXnJ/bin/python: can't open file '__main__': [Errno 2] No such file or directory

**Comment by mzmznasipadang** [comment]
Actually it already can process, but I do need to create a new directory called __main__

**Comment by valeriosouza** [comment]
can you help me how to solve this? @mzmznasipadang

**Comment by rcbonz** [comment]
What command did you use to run __main__.py? That's what works for me:
`pipenv run python3 __main__.py`

**Comment by valeriosouza** [comment]
Hi @rcbonz 

run pipenv run python __main__ and have a error

`root@localhost:~/plane-notify# pipenv run python __main__`

`Traceback (most recent call last):
  File "/usr/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/root/plane-notify/__main__/__main__.py", line 3, in <module>
    from colorama import Fore, Back, Style
ModuleNotFoundError: No module named 'colorama'
`

**Comment by rcbonz** [comment]
Try:
`pip install colorama`
and if that doesn't work:
`pip3 install colorama`
Let me know if it works.

**Comment by valeriosouza** [comment]
I've already done @rcbonz 

`root@localhost:~/plane-notify# pip install colorama
Requirement already satisfied: colorama in /usr/local/lib/python3.9/dist-packages (0.4.4)
root@localhost:~/plane-notify# pip3 install colorama
Requirement already satisfied: colorama in /usr/local/lib/python3.9/dist-packages (0.4.4)
root@localhost:~/plane-notify#
`

**Comment by unrealxqt** [comment]
Did you manage to solve to this? I am getting the same
@valeriosouza
