### ISSUE TITLE
feature request

### ISSUE THREAD

**Issue by cws82us313** [Jxck-S/plane-notify#35]
Hey
It be great if you can code it  so we can use rapidapi.com so it be more cheaper for us.
thanks

**Comment by Jxck-S** [comment]
It could be done, but It wouldn't be easy because you'd have to make an API call per aircraft as ADSBExchanges RapidAPI only accepts one aircraft hex code at a time. If someone else wants to do it go ahead I just don't have time.

**Comment by Jxck-S** [comment]
Moving to #39
