### ISSUE TITLE
Error Exiting: an integer is required (got type NoneType) Failed on C8277E

### ISSUE THREAD

**Issue by cws82us313** [Jxck-S/plane-notify#38]
This message keeps popping up and making the program crash

2022-04-17 07:42:04,755 - an integer is required (got type NoneType)
2022-04-17 07:42:04,756 - Traceback (most recent call last):
  File "/root/RSC/__main__.py", line 163, in <module>
    obj.run_opens(dataState)
  File "/root/RSC/planeClass.py", line 71, in run_opens
    self.last_pos_datetime = datetime.fromtimestamp(ac_dict.time_position)

**Comment by NomsterDude** [comment]
The problem appears to be on line 91 of "planeClass.py". I will provide details below:

Line 91 in planeClass.py: `            self.last_pos_datetime = datetime.fromtimestamp(ac_dict.time_position)`
time_position is undefined and it is unclear whether it is a function or a variable. If it is a function, it needs parentheses. If it is a variable, it needs to be defined either as an argument or a global/local variable.

Edit: After further research and feedback I have found that `time_position` is meant to be a variable aquired from the OpenSky api. This variable has had problems with corruption. It may be possible to create a workaround by checking if `time_position` is "NoneType" and if so, provide a different value either in the form of a default value or a value acquired from a different source.

**Comment by NomsterDude** [comment]
I have created a [pull request](https://github.com/Jxck-S/plane-notify/pull/53) with a potential solution to this issue.

**Comment by Jxck-S** [comment]
I merged the fix.
