### ISSUE TITLE
Mark Shuttleworth Private Jet

### ISSUE THREAD

**Issue by bell-kevin** [Jxck-S/plane-notify#77]
What do you think about making a Twitter account bot for Mark Shuttleworth's private jet?

https://www.airliners.net/photo/Untitled/Bombardier-Global-Express-BD-700-1A10/805262/L

https://en.wikipedia.org/wiki/Mark_Shuttleworth

He has a private jet, a [Bombardier Global Express](https://en.wikipedia.org/wiki/Bombardier_Global_Express), which is often referred to as Canonical One but is in fact owned through his HBD Venture Capital company.[[34]](https://en.wikipedia.org/wiki/Mark_Shuttleworth#cite_note-35)[[35]](https://en.wikipedia.org/wiki/Mark_Shuttleworth#cite_note-36)[[36]](https://en.wikipedia.org/wiki/Mark_Shuttleworth#cite_note-37) The small dragon depicted on the side of the plane near the door is Norman, the HBD Venture Capital mascot.[[37]](https://en.wikipedia.org/wiki/Mark_Shuttleworth#cite_note-38)

**Comment by cws82us313** [comment]
Hey if jack not keen i be keen to help you can discord me on ℭ𝔥𝔯𝔦𝔰 ⑉Smith⑉#4338

**Comment by bell-kevin** [comment]
@cws82us313 Okay! Let's wait a few days to see if he gets back to us.

**Comment by bell-kevin** [comment]
@Jxck-S , what do you say? Should we gone on without you? Or would you be interested in Mark Shuttleworth?

**Comment by bell-kevin** [comment]
@cws82us313 email me at bellKevin@pm.me to get started

**Comment by bell-kevin** [comment]
[https://nitter.net/CopelandJets](https://nitter.net/CopelandJets) and [https://nitter.net/huntsmanJet](https://nitter.net/huntsmanJet)

[https://twitter.com/CopelandJets](https://twitter.com/CopelandJets) and [https://twitter.com/HuntsmanJet](https://twitter.com/HuntsmanJet)

**Comment by Jxck-S** [comment]
Sorry, I just saw this catching up with issues. It looks like you guys got it now. Sad to see Copeland account suspended. LMK on the discord if you want to get these going again.

**Comment by bell-kevin** [comment]
https://twitter.com/huntsmanjet

and

https://nitter.hostux.net/huntsmanjet 

is still going!

We'd love your help!
