### ISSUE TITLE
xdg-open errors when taking screenshot

### ISSUE THREAD

**Issue by makrsmark** [Jxck-S/plane-notify#78]
This doesn't seem to prevent a screenshot from being taken, the logs are being littered with statements when a screenshot is being taken. 

Example:
```
/usr/bin/xdg-open: 882: www-browser: not found
/usr/bin/xdg-open: 882: links2: not found
/usr/bin/xdg-open: 882: elinks: not found
/usr/bin/xdg-open: 882: links: not found
/usr/bin/xdg-open: 882: lynx: not found
/usr/bin/xdg-open: 882: w3m: not found
xdg-open: no method available for opening '/tmp/tmp_4uaq8w5.PNG'

```

I believe this is caused by f600964f931873cccb885b57f1e7cc506be9b642 but haven't dug enough to know for sure

**Comment by Jxck-S** [comment]
I've seen this too I don't know why.

**Comment by Jxck-S** [comment]
Are using docker to run the program? I use systemd and launch it and same issue. I think this may fix (https://unix.stackexchange.com/questions/579771/xdg-open-no-method-available-for-opening-crontab) going to try on my end

**Comment by Jxck-S** [comment]
I think I've solved it selenium is trying to open the screenshot for some reason, changing `browser.save_screenshot(file_path)` to `browser.get_screenshot_as_file(file_path)` seems to fix it. The difference isn't well documented between those methods as far as i looked. Will push the fix once I verify.

**Comment by makrsmark** [comment]
awesome! I am using docker and will try that fix later today.

**Comment by Jxck-S** [comment]
I thought either of those would fix it but I don't think so. Looks like something like this might. Did either of those fix it? https://www.reddit.com/r/commandline/comments/ou3yyo/how_to_handle_browser_opens_from_headless/

**Comment by Jxck-S** [comment]
I think we thought this was from taking the screenshot, but in `modify_image.py ` we have 'image. show()` which opens the image which is not needed, that mightv've caused it. I removed it in my code a while ago but need to upload it.
