### ISSUE TITLE
Feature request: Mastodon API

### ISSUE THREAD

**Issue by eichkat3r** [Jxck-S/plane-notify#88]
The fediverse is gaining a lot of attention lately, with microblogging services like Mastodon and Pleroma being recognized as potential Twitter alternatives. Hence, it would be cool to connect plane-notify to the fedi as well.

For the sake of simplicity, I'd suggest to use Mastodon.py (https://mastodonpy.readthedocs.io/en/stable/), as it is very simple to set up.

What needs to be done to accomplish this:

- [ ] Include Mastodon API key as a configurable value
- [ ] Create defMastodon module that leverages Mastodon.py to post plane information on the fediverse, similar to way it was posted on Twitter
- [ ] Integrate the defMastodon module such that it can be used by plane-notify (I currently don't know how this is done)
- [ ] Setup instructions
- [ ] Add Mastodon.py to requirements (Pipfile)

**Comment by dayeggpi** [comment]
even more relevant, considering that @Elonjet is now suspended on Twitter :P

**Comment by shamoons** [comment]
What about making it ActivityPub instead? So it'll work across the entire #fediverse

**Comment by eichkat3r** [comment]
> What about making it ActivityPub instead? So it'll work across the entire #fediverse

I proposed the Mastodon frontend for a pragmatic reason, as using Mastodon.py to create a toot is essentially 4 lines of code. Also, Mastodon has decent interoperability with other platforms on the fediverse, such as friendica, pleroma or misskey. But I agree, going for ActivityPub directly would be a better choice with respect to generalization to a broader set of platforms on the fediverse. However, creating a generic ActivityPub service implies more effort to develop and test. My suggestion would be to open a separate issue.

**Comment by Jxck-S** [comment]
I'll accept #90 soon and will review it. I actually had not coded this already so thanks! I was manually posting there. Can someone message me in my Discord and explain how ActivityPub/Fediverse would work? New to the decentralized platforms

**Comment by Jxck-S** [comment]
Mastodon was implemented a while ago.
