### ISSUE TITLE
Is there public API for this?

### ISSUE THREAD

**Issue by TrashAccount3424** [Jxck-S/plane-notify#89]
Is there public API for this?

Would make spreading this way easier if there was a public (REST-like) API. 

Also saw in the readme instructions to creating a Telegram  bot. Does such bot exist? Searching on Telegram for possible names shows up a bunch of crypto scams but no bot that actually seems to work.

**Comment by LandonTClipp** [comment]
The public API is just downloading the code and running it yourself :)

**Comment by Jxck-S** [comment]
Are you looking for ElonJet on Telegram?  if so https://t.me/+DVhwNTlOodY4OGFh
Other ElonJet links are here https://grndcntrl.net/links/
Currently no API I've made really I plan on Integrating a database soon but I really don't have the time for an API right now.
