### ISSUE TITLE
❤️

### ISSUE THREAD

**Issue by MarketingPip** [Jxck-S/plane-notify#93]
Well Jack. I'm sending love regarding this project & the way you have not budged. 

I hope any fears of being sued etc (which seem doubtful.) do not budge your project or stance. 👌

Pretty ironic someone that claims to be pro - free speech has literally went out of their ways to make rules on their platform to limit a CERTAIN piece of content that MIGHT or MIGHT NOT affect their life. 

(for anyone reading this - Twitter has added a rule that bans any post that shares live location data... hmmm I wonder why? Who might be upset bout this? 😂😭)

One might argue they don't want a Tesla car seeing them on the street incase a rogue employee etc gets access to the data and is able to TRACK you down from your generalized location last known from a Tesla Car etc...

My support is with you and I'm sure MANY other people in the software and other communities respect your decision to not CONFORM.✌️ 

I think / hope you stick this through. I have a feeling you'll get a lot more than one car as requested. (Probably woulda cost him / her less too.) 

> Anyways sorry for the rant / issue but I have been following this repo and the story closely since it has started.

**Comment by therealbluepandabear** [comment]
You guys are purposefully going around Elon's PIA. That is stalking and incredibly creepy.

**Comment by verynewtocode** [comment]
Hope Jack does not end up losing the lawsuit like the "pedo guy"

**Comment by TheAwesome98-Real** [comment]
what pedo guy???

**Comment by verynewtocode** [comment]
> what pedo guy???

https://www.bbc.co.uk/news/world-us-canada-50695593

Read this article. Elon musk once used Twitter to insulate a member of the public

**Comment by Jxck-S** [comment]
Thanks, @MarketingPip !!!

**Comment by MarketingPip** [comment]
> Thanks, @MarketingPip !!!

Good job on pushing things! Seen the Zoom stream. Keep it up.✌️

**Comment by MarketingPip** [comment]
@Jxck-S - well Jack - sending my love again. 


Keep it up. [Song for you to look at!](https://youtube.com/watch?v=aqyxVayvZzE)
